development:
  adapter: postgresql
  database: wsc-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wsc-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wsc-prod
  pool: 5
  timeout: 5000
